<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.8.10 on linux)" generated="20240111 17:32:16.108" rpa="false" schemaversion="4">
<suite id="s1" name="LaunchBrowser" source="/home/ridham/PycharmProjects/webAutomation/Exercise1/Tests/LaunchBrowser.robot">
<test id="s1-t1" name="Ivalid Login" line="29">
<kw name="Launch Browser">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>https://www.saucedemo.com/</arg>
<arg>chrome</arg>
<arg>options=add_experimental_option("detach", True)</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20240111 17:32:16.252" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com/'.</msg>
<msg timestamp="20240111 17:32:16.839" level="WARN">There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Connection reset by peer (os error 104)); using driver found in the cache</msg>
<status status="PASS" starttime="20240111 17:32:16.251" endtime="20240111 17:32:56.994"/>
</kw>
<status status="PASS" starttime="20240111 17:32:16.251" endtime="20240111 17:32:56.994"/>
</kw>
<status status="PASS" starttime="20240111 17:32:16.250" endtime="20240111 17:32:56.995"/>
</test>
<status status="PASS" starttime="20240111 17:32:16.109" endtime="20240111 17:32:56.996"/>
</suite>
<statistics>
<total>
<stat pass="1" fail="0" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" skip="0" id="s1" name="LaunchBrowser">LaunchBrowser</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240111 17:32:16.839" level="WARN">There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Connection reset by peer (os error 104)); using driver found in the cache</msg>
</errors>
</robot>
